package ihm;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import metier.Film;
import modele.ModeleJTableFilm;
import org.apache.commons.net.ftp.FTP;
import org.apache.commons.net.ftp.FTPSClient;

public class FenetreSaisieAffiche extends javax.swing.JDialog {

    private Film film;
    private ModeleJTableFilm leModeleFilm;
    private FTPSClient ftp;
    private String fileChoosed = null;
    private String filePath = null;
    private int numAffiche;

    public FenetreSaisieAffiche(java.awt.Frame parent, Film film, ModeleJTableFilm leModeleFilm, FTPSClient ftp) {
        super(parent, true);
        this.film = film;
        this.leModeleFilm = leModeleFilm;
        this.ftp = ftp;
        initComponents();
        jTextField1.setText(Integer.toString(film.getNumVisa()));
        jTextField2.setText(film.getTitreFilm());
        jTextField3.setText(Integer.toString(film.getAnneeFilm()));
        jTextField4.setText(Integer.toString(film.getNumGenre()));

        try {
            numAffiche = leModeleFilm.getNumAffiche(film.getNumVisa());
            if (numAffiche != 0) {
                //ftp connexion
                FileInputStream fichier;
                fichier = new FileInputStream("src/connexionFTP.properties");
                Properties props = new Properties();
                props.load(fichier);

                ftp.connect("iutdoua-samba.univ-lyon1.fr", 990);
                if (!ftp.login(props.getProperty("username"), props.getProperty("password"))) {
                    throw new Exception("Problème de login au serveur");
                }
                boolean testConnexion = ftp.sendNoOp();
                if (testConnexion == false) {
                    throw new Exception("Echec de la connexion au serveur");
                }
                ftp.setFileType(FTP.BINARY_FILE_TYPE);
                ftp.setFileTransferMode(FTP.BINARY_FILE_TYPE);
                ftp.enterLocalPassiveMode();

                //ftp traitement
                String remoteFile = "/public_html/VOICELA/assets/images/AFFICHE/" + numAffiche + ".jpeg";
                FileOutputStream outStream = new FileOutputStream("/temp.jpeg");

                ftp.retrieveFile(remoteFile, outStream);
                outStream.flush();
                outStream.close();

                ImageIcon image = new ImageIcon(new ImageIcon("/temp.jpeg").getImage().getScaledInstance(250, 350, Image.SCALE_DEFAULT));
                jLabel6.setIcon(image);
                ftp.disconnect();
            } else {
                jLabel6.setText("Aucune affiche pour le moment");
            }

        } catch (Exception e) {
            try {
                ftp.disconnect();
            } catch (IOException ex) {
                Logger.getLogger(FenetreSaisieAffiche.class.getName()).log(Level.SEVERE, null, ex);
            }
            Logger.getLogger(FenetreApplication.class.getName()).log(Level.SEVERE, null, e);
        }
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        ButtonSelectionFichier = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        ButtonUpload = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        ButtonDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 0, 51));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gestion Affiche Film");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Film selectionné"));

        jLabel2.setText("Numéro visa :");

        jLabel3.setText("Titre :");

        jLabel4.setText("Année :");

        jLabel5.setText("Genre :");

        jTextField1.setEditable(false);

        jTextField2.setEditable(false);

        jTextField3.setEditable(false);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addComponent(jTextField2)
                    .addComponent(jTextField3)
                    .addComponent(jTextField4))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setText("jLabel6");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Ajouter / Modifier / Supprimer affiche"));

        ButtonSelectionFichier.setText("Selectionner une photo");
        ButtonSelectionFichier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSelectionFichierActionPerformed(evt);
            }
        });

        jTextField5.setEditable(false);

        ButtonUpload.setText("Ajouter / Modifier");
        ButtonUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonUploadActionPerformed(evt);
            }
        });

        ButtonDelete.setText("Supprimer affiche");
        ButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jTextField5)
                    .addComponent(ButtonUpload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonSelectionFichier, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                    .addComponent(ButtonDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButtonSelectionFichier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonUpload)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonDelete)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField3ActionPerformed

    private void ButtonSelectionFichierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSelectionFichierActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG", "jpg", "jpeg");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            //System.out.println("You chose to open this file: " + chooser.getSelectedFile().getName());
            fileChoosed = chooser.getSelectedFile().getName();
            filePath = chooser.getSelectedFile().getAbsolutePath();
        }
        jTextField5.setText(fileChoosed);
    }//GEN-LAST:event_ButtonSelectionFichierActionPerformed

    private void ButtonUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonUploadActionPerformed
        // TODO add your handling code here:
        try {

            leModeleFilm.ajouterAfficheFilm(film.getNumVisa());
            int fileNum = leModeleFilm.getLastNumSeqAffiche();
            String fileName = Integer.toString(fileNum);

            //ftp connexion
            FileInputStream fichier;
            fichier = new FileInputStream("src/connexionFTP.properties");
            Properties props = new Properties();
            props.load(fichier);

            ftp.connect("iutdoua-samba.univ-lyon1.fr", 990);
            if (!ftp.login(props.getProperty("username"), props.getProperty("password"))) {
                throw new Exception("Problème de login au serveur");
            }
            boolean testConnexion = ftp.sendNoOp();
            if (testConnexion == false) {
                throw new Exception("Echec de la connexion au serveur");
            }
            ftp.setFileType(FTP.BINARY_FILE_TYPE);
            ftp.setFileTransferMode(FTP.BINARY_FILE_TYPE);
            ftp.enterLocalPassiveMode();

            //ftp
            InputStream input = new FileInputStream(new File(filePath));

            try {
                if (ftp.storeFile("/public_html/VOICELA/assets/images/AFFICHE/" + fileName + ".jpeg", input)) {
                    JOptionPane.showMessageDialog(null, "Affiche ajoutée avec succès", "Information", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    throw new Exception("storeFile a retourner false");
                }
            } catch (Exception e) {
                leModeleFilm.supprimerAffiche(film.getNumVisa());
                JOptionPane.showMessageDialog(null, "Problème à l'upload du fichier, Veuillez réessayer ! : " + e.getMessage(), "Avertissement", JOptionPane.INFORMATION_MESSAGE);
            }

            String remoteFile = "/public_html/VOICELA/assets/images/AFFICHE/" + fileName + ".jpeg";
            FileOutputStream outStream = new FileOutputStream("/temp.jpeg");

            ftp.retrieveFile(remoteFile, outStream);
            outStream.flush();
            outStream.close();

            ImageIcon image = new ImageIcon(new ImageIcon("/temp.jpeg").getImage().getScaledInstance(250, 350, Image.SCALE_DEFAULT));
            jLabel6.setIcon(image);
            ftp.disconnect();

        } catch (Exception e) {
            try {
                ftp.disconnect();
            } catch (IOException ex) {
                Logger.getLogger(FenetreSaisieAffiche.class.getName()).log(Level.SEVERE, null, ex);
            }
            Logger.getLogger(FenetreApplication.class.getName()).log(Level.SEVERE, null, e);
        }

    }//GEN-LAST:event_ButtonUploadActionPerformed

    private void ButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeleteActionPerformed
        // TODO add your handling code here:
        try {
            //ftp connexion
            FileInputStream fichier;
            fichier = new FileInputStream("src/connexionFTP.properties");
            Properties props = new Properties();
            props.load(fichier);

            ftp.connect("iutdoua-samba.univ-lyon1.fr", 990);
            if (!ftp.login(props.getProperty("username"), props.getProperty("password"))) {
                throw new Exception("Problème de login au serveur");
            }
            boolean testConnexion = ftp.sendNoOp();
            if (testConnexion == false) {
                throw new Exception("Echec de la connexion au serveur");
            }
            ftp.setFileType(FTP.BINARY_FILE_TYPE);
            ftp.setFileTransferMode(FTP.BINARY_FILE_TYPE);
            ftp.enterLocalPassiveMode();

            boolean resultat = ftp.deleteFile("/public_html/VOICELA/assets/images/AFFICHE/" + numAffiche + ".jpeg");
            if (resultat) {
                leModeleFilm.supprimerAffiche(film.getNumVisa());
                System.out.println("Le Fichier a été supprimé");
            } else {
                System.out.println("Impossible de supprimer le fichier");
            }
            jLabel6.setIcon(null);
            jLabel6.setText("Aucune affiche pour le moment");
            ftp.disconnect();

        } catch (Exception e) {
            try {
                ftp.disconnect();
            } catch (IOException ex) {
                Logger.getLogger(FenetreSaisieAffiche.class.getName()).log(Level.SEVERE, null, ex);
            }
            Logger.getLogger(FenetreApplication.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_ButtonDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDelete;
    private javax.swing.JButton ButtonSelectionFichier;
    private javax.swing.JButton ButtonUpload;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
