package ihm;

import accesAuxDonnees.DaoEvenement;
import accesAuxDonnees.DaoFilm;
import accesAuxDonnees.DaoVip;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import metier.Evenement;
import metier.Film;
import metier.Vip;
import modele.ModeleJTableVip;
import modele.ModeleJTableAddMariage;
import modele.ModeleJTableEvenement;
import modele.ModeleJTableFilm;
import modele.ModeleJTableGenreFilm;
import org.apache.commons.net.ftp.FTP;
import org.apache.commons.net.ftp.FTPSClient;

public class FenetreApplication extends javax.swing.JFrame {

    private Connection laConnexion;
    private FTPSClient ftp;

    private DaoVip leDaoVip;
    private DaoEvenement leDaoEvenement;
    private DaoFilm leDaoFilm;

    private ModeleJTableVip leModeleVip;
    private ModeleJTableEvenement leModeleEvenement;
    private ModeleJTableFilm leModeleFilm;
    private ModeleJTableGenreFilm leModeleGenreFilm;

    public FenetreApplication(DaoVip leDaoVip, DaoEvenement leDaoEvenement, DaoFilm leDaoFilm, Connection laConnexion) throws SQLException {

        this.laConnexion = laConnexion;
        ftp = new FTPSClient();

        this.leDaoVip = leDaoVip;
        this.leDaoEvenement = leDaoEvenement;
        this.leDaoFilm = leDaoFilm;

        this.leModeleVip = new ModeleJTableVip(leDaoVip);
        this.leModeleEvenement = new ModeleJTableEvenement(leDaoEvenement, leModeleVip);
        this.leModeleGenreFilm = new ModeleJTableGenreFilm(leDaoFilm);
        this.leModeleFilm = new ModeleJTableFilm(leDaoFilm, leModeleGenreFilm);

        initComponents();

        try {
            leModeleGenreFilm.chargerGenre();
            leModeleVip.chargerLesVip();
            leModeleEvenement.chargerLesEvenement();
            leModeleFilm.chargerLesFilm();

            nbVipBase.setText(Integer.toString(leModeleVip.getNbVip()) + " VIP dans la base");
            nbMariageBase.setText(Integer.toString(leModeleEvenement.getNbEvenement()) + " Mariages dans la base");
            jLabel7.setText(Integer.toString(leModeleFilm.getNbFilm()) + " Films dans la base");

        } catch (Exception e) {
            Logger.getLogger(FenetreApplication.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        Pane = new javax.swing.JTabbedPane();
        panelVip = new javax.swing.JPanel();
        ButtonRefreshVip = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txRecherche = new javax.swing.JTextField();
        ButtonSearchVip = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVip = new javax.swing.JTable();
        ButtonPhotoVip = new javax.swing.JButton();
        ButtonDeleteVip = new javax.swing.JButton();
        panelFonctionsVip = new javax.swing.JPanel();
        ButtonAddVip = new javax.swing.JButton();
        nbVipBase = new javax.swing.JLabel();
        ButtonCommentVip = new javax.swing.JButton();
        panelMariage = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableMariage = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        ButtonSearchMariage = new javax.swing.JToggleButton();
        ButtonAddDivorce = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        ButtonAddMariage = new javax.swing.JButton();
        ButtonRefreshMariage = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        nbMariageBase = new javax.swing.JLabel();
        ButtonDeleteMariage = new javax.swing.JButton();
        panelFilm = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableFilm = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        ButtonGenre = new javax.swing.JButton();
        ButtonRealisation = new javax.swing.JButton();
        ButtonAddFilm = new javax.swing.JButton();
        ButtonRefreshFilm = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        ButtonSearchFilm = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        ButtonAfficheFilm = new javax.swing.JButton();
        ButtonDeleteFilm = new javax.swing.JButton();
        ButtonCommentFilm = new javax.swing.JButton();
        panelAPropos = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Affichage des VIP");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        Pane.setForeground(new java.awt.Color(204, 0, 51));
        Pane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Pane.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Pane.setOpaque(true);
        Pane.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PaneFocusGained(evt);
            }
        });

        ButtonRefreshVip.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        ButtonRefreshVip.setForeground(new java.awt.Color(204, 0, 51));
        ButtonRefreshVip.setText("Réinitialiser");
        ButtonRefreshVip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRefreshVipActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel1.setText("Recherche :");

        ButtonSearchVip.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        ButtonSearchVip.setForeground(new java.awt.Color(204, 0, 51));
        ButtonSearchVip.setText("Rechercher");
        ButtonSearchVip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSearchVipActionPerformed(evt);
            }
        });

        tableVip.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tableVip.setModel(leModeleVip);
        tableVip.setSelectionBackground(new java.awt.Color(204, 0, 51));
        jScrollPane1.setViewportView(tableVip);

        ButtonPhotoVip.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        ButtonPhotoVip.setForeground(new java.awt.Color(204, 0, 51));
        ButtonPhotoVip.setText("Gestion photo VIP");
        ButtonPhotoVip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPhotoVipActionPerformed(evt);
            }
        });

        ButtonDeleteVip.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        ButtonDeleteVip.setForeground(new java.awt.Color(204, 0, 51));
        ButtonDeleteVip.setText("Supprimer VIP");
        ButtonDeleteVip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeleteVipActionPerformed(evt);
            }
        });

        panelFonctionsVip.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fonctions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 12), new java.awt.Color(204, 0, 51))); // NOI18N

        ButtonAddVip.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        ButtonAddVip.setForeground(new java.awt.Color(204, 0, 51));
        ButtonAddVip.setText("Ajouter VIP");
        ButtonAddVip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddVipActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFonctionsVipLayout = new javax.swing.GroupLayout(panelFonctionsVip);
        panelFonctionsVip.setLayout(panelFonctionsVipLayout);
        panelFonctionsVipLayout.setHorizontalGroup(
            panelFonctionsVipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ButtonAddVip, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
        );
        panelFonctionsVipLayout.setVerticalGroup(
            panelFonctionsVipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ButtonAddVip)
        );

        nbVipBase.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        nbVipBase.setText("jLabel2");

        ButtonCommentVip.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        ButtonCommentVip.setForeground(new java.awt.Color(204, 0, 51));
        ButtonCommentVip.setText("Commentaire VIP");
        ButtonCommentVip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCommentVipActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelVipLayout = new javax.swing.GroupLayout(panelVip);
        panelVip.setLayout(panelVipLayout);
        panelVipLayout.setHorizontalGroup(
            panelVipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVipLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVipLayout.createSequentialGroup()
                        .addComponent(ButtonPhotoVip)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonCommentVip)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonDeleteVip)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nbVipBase))
                    .addGroup(panelVipLayout.createSequentialGroup()
                        .addComponent(ButtonRefreshVip)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txRecherche)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonSearchVip))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(panelFonctionsVip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelVipLayout.setVerticalGroup(
            panelVipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVipLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonRefreshVip)
                    .addComponent(jLabel1)
                    .addComponent(txRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonSearchVip))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelVipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                    .addGroup(panelVipLayout.createSequentialGroup()
                        .addComponent(panelFonctionsVip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelVipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonPhotoVip)
                    .addComponent(ButtonDeleteVip)
                    .addComponent(nbVipBase)
                    .addComponent(ButtonCommentVip))
                .addContainerGap())
        );

        Pane.addTab("Affichage des VIP", new javax.swing.ImageIcon("D:\\Drédré\\Desktop\\iconVip.png"), panelVip); // NOI18N

        tableMariage.setModel(leModeleEvenement);
        tableMariage.setSelectionBackground(new java.awt.Color(0, 153, 153));
        jScrollPane2.setViewportView(tableMariage);

        ButtonSearchMariage.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        ButtonSearchMariage.setForeground(new java.awt.Color(204, 0, 51));
        ButtonSearchMariage.setText("Rechercher");
        ButtonSearchMariage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSearchMariageActionPerformed(evt);
            }
        });

        ButtonAddDivorce.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        ButtonAddDivorce.setForeground(new java.awt.Color(204, 0, 51));
        ButtonAddDivorce.setText("Ajouter divorce");
        ButtonAddDivorce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddDivorceActionPerformed(evt);
            }
        });

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fonctions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 12), new java.awt.Color(204, 0, 51))); // NOI18N
        jPanel8.setForeground(new java.awt.Color(204, 0, 51));

        ButtonAddMariage.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        ButtonAddMariage.setForeground(new java.awt.Color(204, 0, 51));
        ButtonAddMariage.setText("Ajouter Mariage");
        ButtonAddMariage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddMariageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ButtonAddMariage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ButtonAddMariage)
        );

        ButtonRefreshMariage.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ButtonRefreshMariage.setForeground(new java.awt.Color(204, 0, 51));
        ButtonRefreshMariage.setText("Réinitialiser");
        ButtonRefreshMariage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRefreshMariageActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel4.setText("Recherche :");

        nbMariageBase.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        nbMariageBase.setText("jLabel6");

        ButtonDeleteMariage.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        ButtonDeleteMariage.setForeground(new java.awt.Color(204, 0, 51));
        ButtonDeleteMariage.setText("Supprimer mariage");
        ButtonDeleteMariage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeleteMariageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMariageLayout = new javax.swing.GroupLayout(panelMariage);
        panelMariage.setLayout(panelMariageLayout);
        panelMariageLayout.setHorizontalGroup(
            panelMariageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMariageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMariageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMariageLayout.createSequentialGroup()
                        .addComponent(ButtonAddDivorce)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonDeleteMariage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nbMariageBase))
                    .addGroup(panelMariageLayout.createSequentialGroup()
                        .addComponent(ButtonRefreshMariage)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonSearchMariage))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelMariageLayout.setVerticalGroup(
            panelMariageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMariageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMariageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonSearchMariage)
                    .addComponent(ButtonRefreshMariage)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMariageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMariageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonAddDivorce)
                    .addComponent(nbMariageBase)
                    .addComponent(ButtonDeleteMariage))
                .addContainerGap())
        );

        Pane.addTab("Affichage des Mariages", new javax.swing.ImageIcon("D:\\Drédré\\Desktop\\iconMariage.png"), panelMariage); // NOI18N

        tableFilm.setModel(leModeleFilm);
        tableFilm.setSelectionBackground(new java.awt.Color(0, 153, 153));
        jScrollPane3.setViewportView(tableFilm);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fonctions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 12), new java.awt.Color(204, 0, 51))); // NOI18N

        ButtonGenre.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        ButtonGenre.setForeground(new java.awt.Color(204, 0, 51));
        ButtonGenre.setText("Gérer les genres");
        ButtonGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonGenreActionPerformed(evt);
            }
        });

        ButtonRealisation.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        ButtonRealisation.setForeground(new java.awt.Color(204, 0, 51));
        ButtonRealisation.setText("Gérer les réalisations");
        ButtonRealisation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRealisationActionPerformed(evt);
            }
        });

        ButtonAddFilm.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        ButtonAddFilm.setForeground(new java.awt.Color(204, 0, 51));
        ButtonAddFilm.setText("Ajouter un Film");
        ButtonAddFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddFilmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ButtonGenre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ButtonRealisation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
            .addComponent(ButtonAddFilm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(ButtonAddFilm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonRealisation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonGenre))
        );

        ButtonRefreshFilm.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        ButtonRefreshFilm.setForeground(new java.awt.Color(204, 0, 51));
        ButtonRefreshFilm.setText("Réinitialiser");
        ButtonRefreshFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRefreshFilmActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel5.setText("Recherche :");

        ButtonSearchFilm.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        ButtonSearchFilm.setForeground(new java.awt.Color(204, 0, 51));
        ButtonSearchFilm.setText("Rechercher");
        ButtonSearchFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSearchFilmActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 12)); // NOI18N
        jLabel7.setText("jLabel7");

        ButtonAfficheFilm.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        ButtonAfficheFilm.setForeground(new java.awt.Color(204, 0, 51));
        ButtonAfficheFilm.setText("Gérer Affiche");
        ButtonAfficheFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAfficheFilmActionPerformed(evt);
            }
        });

        ButtonDeleteFilm.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        ButtonDeleteFilm.setForeground(new java.awt.Color(204, 0, 51));
        ButtonDeleteFilm.setText("Supprimer film");
        ButtonDeleteFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeleteFilmActionPerformed(evt);
            }
        });

        ButtonCommentFilm.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        ButtonCommentFilm.setForeground(new java.awt.Color(204, 0, 51));
        ButtonCommentFilm.setText("Commentaire Film");
        ButtonCommentFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCommentFilmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFilmLayout = new javax.swing.GroupLayout(panelFilm);
        panelFilm.setLayout(panelFilmLayout);
        panelFilmLayout.setHorizontalGroup(
            panelFilmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFilmLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFilmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFilmLayout.createSequentialGroup()
                        .addComponent(ButtonAfficheFilm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonCommentFilm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonDeleteFilm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFilmLayout.createSequentialGroup()
                        .addComponent(ButtonRefreshFilm)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonSearchFilm))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelFilmLayout.setVerticalGroup(
            panelFilmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFilmLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFilmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonRefreshFilm)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonSearchFilm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFilmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFilmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonAfficheFilm)
                    .addGroup(panelFilmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(ButtonDeleteFilm)
                        .addComponent(ButtonCommentFilm)))
                .addContainerGap())
        );

        Pane.addTab("Affichage des Films", new javax.swing.ImageIcon("D:\\Drédré\\Desktop\\iconFilm.png"), panelFilm); // NOI18N

        javax.swing.GroupLayout panelAProposLayout = new javax.swing.GroupLayout(panelAPropos);
        panelAPropos.setLayout(panelAProposLayout);
        panelAProposLayout.setHorizontalGroup(
            panelAProposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );
        panelAProposLayout.setVerticalGroup(
            panelAProposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 373, Short.MAX_VALUE)
        );

        Pane.addTab("A propos", new javax.swing.ImageIcon("D:\\Drédré\\Desktop\\iconInfo.png"), panelAPropos); // NOI18N

        jPanel4.setBackground(new java.awt.Color(204, 0, 51));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("VOICELA Admin Application");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pane)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Pane)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int reponse = JOptionPane.showConfirmDialog(this, "Voulez vraiment quitter ?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (reponse == JOptionPane.YES_OPTION) {
            try {
                laConnexion.close();
            } catch (SQLException ex) {
                Logger.getLogger(FenetreApplication.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    private void ButtonAddDivorceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddDivorceActionPerformed
        // TODO add your handling code here:
        try {
            int ligne = tableMariage.getSelectedRow();
            if (ligne == -1) {
                throw new Exception("Aucune ligne selectionnée");
            }
            Evenement divorce = leModeleEvenement.getEvenement(ligne);
            String reponse = JOptionPane.showInputDialog(this, "Entrer la date du divorce (dd/mm/yyyy) et valider", "Confirmation", JOptionPane.OK_CANCEL_OPTION);

            if (reponse != null) {
                DateFormat format = new SimpleDateFormat("dd/MM/yyyy");
                Date date = format.parse(reponse);
                java.sql.Date sqlDate = new java.sql.Date(date.getTime());
                divorce.setDateDivorce(sqlDate);

                try {
                    leModeleEvenement.addDivorce(divorce);
                } catch (Exception e) {
                    throw new Exception("Problème à l'insertion du divorce");
                }

            } else {
                throw new Exception("Vous avez annulé l'ajout du divorce");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erreur à l'ajout du divorce : " + e.getMessage(), JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_ButtonAddDivorceActionPerformed

    private void ButtonAddVipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddVipActionPerformed
        // TODO add your handling code here:
        try {
            Vip vip = new Vip();
            FenetreSaisieVip laSaisie = new FenetreSaisieVip(this, vip);
            if (laSaisie.doModal() == true) {
                boolean testPays = leDaoVip.checkPays(vip.getNomPays());
                if (testPays == false) {
                    leDaoVip.addPays(vip.getNomPays());
                }
                leModeleVip.insererVip(vip);
                leModeleVip.chargerLesVip();
                nbVipBase.setText(Integer.toString(leModeleVip.getNbVip()) + " VIP dans la base");
            }
        } catch (Exception e) {
            //System.out.println("Exception à l'insertion : " + e.getMessage());
            Logger.getLogger(FenetreApplication.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_ButtonAddVipActionPerformed

    private void ButtonDeleteVipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeleteVipActionPerformed
        // TODO add your handling code here:
        try {
            int ligne = tableVip.getSelectedRow();
            Vip vip = leModeleVip.getVip(ligne);
            if (ligne == -1) {
                throw new Exception("Aucune ligne selectionnée");
            }
            int comfirm = JOptionPane.showConfirmDialog(this, "Comfirmer suppression de : " + vip.getPrenomVip() + " " + vip.getNomVip() + " ?", "Avertissement", JOptionPane.YES_NO_OPTION);
            if (comfirm == 0) {
                leModeleEvenement.supprimerEvenementVip(vip.getNumVip());
                leModeleVip.supprimerVip(ligne);
                leModeleVip.supprimerPhotoVip(vip,ftp);
                leModeleVip.chargerLesVip();
                leModeleEvenement.chargerLesEvenement();
            }
            nbVipBase.setText(Integer.toString(leModeleVip.getNbVip()) + " VIP dans la base");

        } catch (Exception e) {
            System.out.println("Exception à la suppression : " + e.getMessage());
        }
    }//GEN-LAST:event_ButtonDeleteVipActionPerformed

    private void ButtonPhotoVipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPhotoVipActionPerformed
        // TODO add your handling code here:
        try {
            if (tableVip.getSelectedRow() == -1) {
                throw new Exception("Aucune ligne VIP selectionnée");
            }
            int ligne = tableVip.getSelectedRow();
            Vip vip = leModeleVip.getVip(ligne);
            
            

            FenetreSaisiePhoto laSaisiePhoto = new FenetreSaisiePhoto(this, vip, leDaoVip, ftp);

        } catch (Exception e) {
            System.out.println("Exception à l'insertion : " + e.getMessage());
        }
    }//GEN-LAST:event_ButtonPhotoVipActionPerformed

    private void ButtonSearchVipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSearchVipActionPerformed
        // TODO add your handling code here:
        try {
            leModeleVip.chargerLesVip(txRecherche.getText());
        } catch (SQLException ex) {
            Logger.getLogger(FenetreSaisieMariage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ButtonSearchVipActionPerformed

    private void ButtonRefreshVipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRefreshVipActionPerformed
        try {
            leModeleVip.chargerLesVip();
        } catch (Exception ex) {
            Logger.getLogger(FenetreApplication.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ButtonRefreshVipActionPerformed

    private void ButtonAddMariageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddMariageActionPerformed
        // TODO add your handling code here:
        try {
            Evenement evenementAddMariage = new Evenement();
            FenetreSaisieMariage laSaisieMariage = new FenetreSaisieMariage(this, evenementAddMariage, leModeleVip, leDaoVip, leModeleEvenement);
            if (laSaisieMariage.doModal() == true) {
                JOptionPane.showMessageDialog(null, "Mariage ajouté avec succès", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
            nbMariageBase.setText(Integer.toString(leModeleEvenement.getNbEvenement()) + " Mariages dans la base");
        } catch (Exception ex) {
            Logger.getLogger(FenetreApplication.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_ButtonAddMariageActionPerformed

    private void PaneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PaneFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_PaneFocusGained

    private void ButtonAddFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddFilmActionPerformed
        // TODO add your handling code here:
        try {
            Film film = new Film();
            FenetreSaisieFilm laSaisieFilm = new FenetreSaisieFilm(this, film, leDaoFilm);
            if (laSaisieFilm.doModal() == true) {
                leModeleFilm.ajouterFilm(film);
            }
            jLabel7.setText(Integer.toString(leModeleFilm.getNbFilm()) + " Films dans la base");
        } catch (Exception e) {
            //System.out.println("Exception à l'ajout du film : " + e.getMessage());
            Logger.getLogger(FenetreApplication.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_ButtonAddFilmActionPerformed

    private void ButtonGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonGenreActionPerformed
        // TODO add your handling code here:
        try {
            FenetreSaisieGenre laVueGenre = new FenetreSaisieGenre(this, leModeleGenreFilm);
        } catch (Exception e) {
            //System.out.println("Exception à l'ajout du film : " + e.getMessage());
            Logger.getLogger(FenetreApplication.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_ButtonGenreActionPerformed

    private void ButtonRealisationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRealisationActionPerformed
        // TODO add your handling code here:
        try {
            FenetreRealisation laVueRealisation = new FenetreRealisation(this, leModeleFilm, leModeleGenreFilm, leDaoFilm);
        } catch (Exception e) {
            //System.out.println("Exception à l'ajout du film : " + e.getMessage());
            Logger.getLogger(FenetreApplication.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_ButtonRealisationActionPerformed

    private void ButtonSearchMariageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSearchMariageActionPerformed
        try {
            leModeleEvenement.chargerLesEvenement(jTextField1.getText());
        } catch (SQLException ex) {
            Logger.getLogger(FenetreApplication.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ButtonSearchMariageActionPerformed

    private void ButtonRefreshMariageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRefreshMariageActionPerformed
        // TODO add your handling code here:
        try {
            leModeleEvenement.chargerLesEvenement();
        } catch (SQLException ex) {
            Logger.getLogger(FenetreApplication.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ButtonRefreshMariageActionPerformed

    private void ButtonSearchFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSearchFilmActionPerformed
        // TODO add your handling code here:
        try {
            leModeleFilm.chargerLesFilm(jTextField3.getText());
        } catch (SQLException ex) {
            Logger.getLogger(FenetreApplication.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ButtonSearchFilmActionPerformed

    private void ButtonRefreshFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRefreshFilmActionPerformed
        // TODO add your handling code here:
        try {
            leModeleFilm.chargerLesFilm();
        } catch (SQLException ex) {
            Logger.getLogger(FenetreApplication.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ButtonRefreshFilmActionPerformed

    private void ButtonAfficheFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAfficheFilmActionPerformed
        // TODO add your handling code here:
        try{
            int ligne = tableFilm.getSelectedRow();
            Film film = leModeleFilm.getFilm(ligne);
            
            FenetreSaisieAffiche laSaisieAffiche = new FenetreSaisieAffiche(this, film, leModeleFilm, ftp);
            
        }catch (Exception e){
            Logger.getLogger(FenetreApplication.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_ButtonAfficheFilmActionPerformed

    private void ButtonDeleteFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeleteFilmActionPerformed
        // TODO add your handling code here:
        try{
            int ligne = tableFilm.getSelectedRow();
            Film film = leModeleFilm.getFilm(ligne);
            
            int comfirm = JOptionPane.showConfirmDialog(this, "Comfirmer suppression du film  : " + film.getTitreFilm() + " ?", "Avertissement", JOptionPane.YES_NO_OPTION);
            if (comfirm == 0) {
                leModeleFilm.supprimerFilm(film.getNumVisa());
                leModeleFilm.chargerLesFilm();
            }
        }catch (Exception e){
            Logger.getLogger(FenetreApplication.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_ButtonDeleteFilmActionPerformed

    private void ButtonDeleteMariageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeleteMariageActionPerformed
        // TODO add your handling code here:
        try{
            int ligne = tableMariage.getSelectedRow();
            Evenement evenement = leModeleEvenement.getEvenement(ligne);
            
            int comfirm = JOptionPane.showConfirmDialog(this, "Comfirmer suppression du mariage ?", "Avertissement", JOptionPane.YES_NO_OPTION);
            if (comfirm == 0) {
                leModeleEvenement.supprimerEvenement(evenement);
                leModeleEvenement.chargerLesEvenement();
                leModeleVip.chargerLesVip();
            }
        }catch (Exception e){
            Logger.getLogger(FenetreApplication.class.getName()).log(Level.SEVERE, null, e);
        }
        
    }//GEN-LAST:event_ButtonDeleteMariageActionPerformed

    private void ButtonCommentVipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCommentVipActionPerformed
        // TODO add your handling code here:
        try {
            int ligne = tableVip.getSelectedRow();
            Vip vip = leModeleVip.getVip(ligne);
            if (ligne == -1) {
                throw new Exception("Aucune ligne selectionnée");
            }
            FenetreSaisieTextVip laSaisieCommentaireVip = new FenetreSaisieTextVip(this, vip, leModeleVip);
        } catch (Exception e) {
            System.out.println("Exception à la suppression : " + e.getMessage());
        }
    }//GEN-LAST:event_ButtonCommentVipActionPerformed

    private void ButtonCommentFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCommentFilmActionPerformed
        // TODO add your handling code here:
        try {
            int ligne = tableFilm.getSelectedRow();
            if (ligne == -1) {
                throw new Exception("Aucune ligne selectionnée");
            }
            Film film = leModeleFilm.getFilm(ligne);
            FenetreSaisieTextFilm laSaisieCommentaireFilm = new FenetreSaisieTextFilm(this, film, leModeleFilm);

        } catch (Exception e) {
            System.out.println("Exception à la suppression : " + e.getMessage());
        }
    }//GEN-LAST:event_ButtonCommentFilmActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAddDivorce;
    private javax.swing.JButton ButtonAddFilm;
    private javax.swing.JButton ButtonAddMariage;
    private javax.swing.JButton ButtonAddVip;
    private javax.swing.JButton ButtonAfficheFilm;
    private javax.swing.JButton ButtonCommentFilm;
    private javax.swing.JButton ButtonCommentVip;
    private javax.swing.JButton ButtonDeleteFilm;
    private javax.swing.JButton ButtonDeleteMariage;
    private javax.swing.JButton ButtonDeleteVip;
    private javax.swing.JButton ButtonGenre;
    private javax.swing.JButton ButtonPhotoVip;
    private javax.swing.JButton ButtonRealisation;
    private javax.swing.JButton ButtonRefreshFilm;
    private javax.swing.JButton ButtonRefreshMariage;
    private javax.swing.JButton ButtonRefreshVip;
    private javax.swing.JButton ButtonSearchFilm;
    private javax.swing.JToggleButton ButtonSearchMariage;
    private javax.swing.JButton ButtonSearchVip;
    private javax.swing.JTabbedPane Pane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel nbMariageBase;
    private javax.swing.JLabel nbVipBase;
    private javax.swing.JPanel panelAPropos;
    private javax.swing.JPanel panelFilm;
    private javax.swing.JPanel panelFonctionsVip;
    private javax.swing.JPanel panelMariage;
    private javax.swing.JPanel panelVip;
    private javax.swing.JTable tableFilm;
    private javax.swing.JTable tableMariage;
    private javax.swing.JTable tableVip;
    private javax.swing.JTextField txRecherche;
    // End of variables declaration//GEN-END:variables
}
